// Code generated by "stringer -type=MutationType"; DO NOT EDIT

package mutate

import "fmt"

const _MutationType_name = "MutateSetMutatePushMutatePullMutateTruncateMutateIdxMutateUnset"

var _MutationType_index = [...]uint8{0, 9, 19, 29, 43, 52, 63}

func (i MutationType) String() string {
	if i < 0 || i >= MutationType(len(_MutationType_index)-1) {
		return fmt.Sprintf("MutationType(%d)", i)
	}
	return _MutationType_name[_MutationType_index[i]:_MutationType_index[i+1]]
}
